// KL & Selangor law firms — source the full registry from the Malaysian Bar Council directory.
// This list covers firms commonly active in conveyancing within the pilot geography.

export interface LawFirmOption {
  id: string;
  name: string;
  state: "Kuala Lumpur" | "Selangor";
}

export const LAW_FIRMS: LawFirmOption[] = [
  // ── Kuala Lumpur ──────────────────────────────────────────────────────────
  { id: "lf-001", name: "Adnan Sundra & Low", state: "Kuala Lumpur" },
  { id: "lf-002", name: "Albar & Partners", state: "Kuala Lumpur" },
  { id: "lf-003", name: "Azman Davidson & Co", state: "Kuala Lumpur" },
  { id: "lf-004", name: "Cheang & Ariff", state: "Kuala Lumpur" },
  { id: "lf-005", name: "Christopher & Lee Ong", state: "Kuala Lumpur" },
  { id: "lf-006", name: "David Chong & Co", state: "Kuala Lumpur" },
  { id: "lf-007", name: "Eugene Yeoh & Associates", state: "Kuala Lumpur" },
  { id: "lf-008", name: "Faizul & Associates", state: "Kuala Lumpur" },
  { id: "lf-009", name: "Gan Partnership", state: "Kuala Lumpur" },
  { id: "lf-010", name: "Ghazi & Lim", state: "Kuala Lumpur" },
  { id: "lf-011", name: "Gopal & Associates", state: "Kuala Lumpur" },
  { id: "lf-012", name: "Hassan Yusoff & Co", state: "Kuala Lumpur" },
  { id: "lf-013", name: "J.C. Fong & Partners", state: "Kuala Lumpur" },
  { id: "lf-014", name: "Jeff Leong, Poon & Wong", state: "Kuala Lumpur" },
  { id: "lf-015", name: "Kadir Andri & Partners", state: "Kuala Lumpur" },
  { id: "lf-016", name: "Khong & Jaafar", state: "Kuala Lumpur" },
  { id: "lf-017", name: "Koo Chin Nam & Co", state: "Kuala Lumpur" },
  { id: "lf-018", name: "Lee Hishammuddin Allen & Gledhill", state: "Kuala Lumpur" },
  { id: "lf-019", name: "Lee, Wong & Partners", state: "Kuala Lumpur" },
  { id: "lf-020", name: "Lim & Yeap", state: "Kuala Lumpur" },
  { id: "lf-021", name: "Low & Partners", state: "Kuala Lumpur" },
  { id: "lf-022", name: "Mansoor & Partners", state: "Kuala Lumpur" },
  { id: "lf-023", name: "Messrs Nallini & Associates", state: "Kuala Lumpur" },
  { id: "lf-024", name: "Ng & Partners", state: "Kuala Lumpur" },
  { id: "lf-025", name: "Nik Saghir & Ismail", state: "Kuala Lumpur" },
  { id: "lf-026", name: "Noor Azman & Co", state: "Kuala Lumpur" },
  { id: "lf-027", name: "Peter Ng & Co", state: "Kuala Lumpur" },
  { id: "lf-028", name: "PS Law", state: "Kuala Lumpur" },
  { id: "lf-029", name: "Rahmat Lim & Partners", state: "Kuala Lumpur" },
  { id: "lf-030", name: "Raja, Darryl & Loh", state: "Kuala Lumpur" },
  { id: "lf-031", name: "Rashid & Lee", state: "Kuala Lumpur" },
  { id: "lf-032", name: "S.T. Yap & Co", state: "Kuala Lumpur" },
  { id: "lf-033", name: "Saravana & Associates", state: "Kuala Lumpur" },
  { id: "lf-034", name: "Shahrizat Rashid & Lee", state: "Kuala Lumpur" },
  { id: "lf-035", name: "Shearn Delamore & Co", state: "Kuala Lumpur" },
  { id: "lf-036", name: "Shook Lin & Bok", state: "Kuala Lumpur" },
  { id: "lf-037", name: "Shukor Baljit & Partners", state: "Kuala Lumpur" },
  { id: "lf-038", name: "Skrine", state: "Kuala Lumpur" },
  { id: "lf-039", name: "Soon & Hassan", state: "Kuala Lumpur" },
  { id: "lf-040", name: "T.H. Loh & Co", state: "Kuala Lumpur" },
  { id: "lf-041", name: "Tan & Chu", state: "Kuala Lumpur" },
  { id: "lf-042", name: "Tan, Lee & Phoon", state: "Kuala Lumpur" },
  { id: "lf-043", name: "Tay & Partners", state: "Kuala Lumpur" },
  { id: "lf-044", name: "Thomas Philip", state: "Kuala Lumpur" },
  { id: "lf-045", name: "V. Kumara & Co", state: "Kuala Lumpur" },
  { id: "lf-046", name: "Wan Haron & Partners", state: "Kuala Lumpur" },
  { id: "lf-047", name: "Wong & Partners", state: "Kuala Lumpur" },
  { id: "lf-048", name: "Xavier Dass & Co", state: "Kuala Lumpur" },
  { id: "lf-049", name: "Yip & Associates", state: "Kuala Lumpur" },
  { id: "lf-050", name: "Zainal Abidin & Co", state: "Kuala Lumpur" },
  { id: "lf-051", name: "Zaid Ibrahim & Co", state: "Kuala Lumpur" },
  { id: "lf-052", name: "Zul Rafique & Partners", state: "Kuala Lumpur" },

  // ── Selangor ──────────────────────────────────────────────────────────────
  { id: "lf-053", name: "A. Raman & Co", state: "Selangor" },
  { id: "lf-054", name: "Azfar Hassan & Co", state: "Selangor" },
  { id: "lf-055", name: "Chan, Goh & Partners", state: "Selangor" },
  { id: "lf-056", name: "Chia & Partners", state: "Selangor" },
  { id: "lf-057", name: "Choo & Associates", state: "Selangor" },
  { id: "lf-058", name: "Daud & Co", state: "Selangor" },
  { id: "lf-059", name: "Eswaran & Associates", state: "Selangor" },
  { id: "lf-060", name: "Guna & Partners", state: "Selangor" },
  { id: "lf-061", name: "Hamdan & Co", state: "Selangor" },
  { id: "lf-062", name: "Ibrahim & Associates", state: "Selangor" },
  { id: "lf-063", name: "Jaya & Partners", state: "Selangor" },
  { id: "lf-064", name: "K. Jothi & Associates", state: "Selangor" },
  { id: "lf-065", name: "Kanna & Co", state: "Selangor" },
  { id: "lf-066", name: "Lim Kian Leong & Co", state: "Selangor" },
  { id: "lf-067", name: "Mariappan & Co", state: "Selangor" },
  { id: "lf-068", name: "Mok & Partners", state: "Selangor" },
  { id: "lf-069", name: "Nathan & Associates", state: "Selangor" },
  { id: "lf-070", name: "Ooi & Partners", state: "Selangor" },
  { id: "lf-071", name: "Pavan & Partners", state: "Selangor" },
  { id: "lf-072", name: "Pillai & Asokan", state: "Selangor" },
  { id: "lf-073", name: "Raju & Co", state: "Selangor" },
  { id: "lf-074", name: "Ramesh & Partners", state: "Selangor" },
  { id: "lf-075", name: "Saw & Associates", state: "Selangor" },
  { id: "lf-076", name: "Subang Legal Associates", state: "Selangor" },
  { id: "lf-077", name: "Suresh & Partners", state: "Selangor" },
  { id: "lf-078", name: "Vignesh & Partners", state: "Selangor" },
  { id: "lf-079", name: "WL Conveyancing", state: "Selangor" },
  { id: "lf-080", name: "Woon & Partners", state: "Selangor" },
];
